  GNU nano 6.2                                                                                    docker-compose.yml                                                                                             services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "6543:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    environment:
      - NODE_ENV=production

volumes:
  dbdata:


